### PR TITLE
Migrate to the Azure publishing gateway as required for Microsoft compliance

### PR DESCRIPTION
**Pull request by luras-oil**
Migrate to the Azure publishing gateway as required for Microsoft compliance.
Add publish.yml for azure pipeline to release new versions.

### CODE REVIEW

**Review by dalemyers — APPROVED** [review]
Change is good, but the CI hasn't run. Worth a look at.

**Comment by levinli303** [comment]
> Change is good, but the CI hasn't run. Worth a look at.

maybe because azure-pipelines.yml is renamed to .azure-pipelines.yml ?

**Comment by dalemyers** [comment]
> > Change is good, but the CI hasn't run. Worth a look at.
> 
> maybe because azure-pipelines.yml is renamed to .azure-pipelines.yml ?

Probably yes. The pipelines on ADO will need to be modified to point at the new definition.

**Comment by luras-oil** [comment]
yeah I was intend to change the definition after this Pr merged

**Review by guojiubo — APPROVED** [review]

**Pull request merged**
